version: 2

sources:
  - name: erp
    description: banco replica adventurework
    schema: adventurework_etl
    tables:
      - name: salesorderdetail

      - name: salesreason
        description:  tabela de razoes de venda
      
      - name: customer
        description:  tabela de Clientes
      
      - name: store
        description:  tabela de Loja    
      
      - name: creditcard
        description:  tabela de cartoes de credito  